// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ88TDrYpt7Kr83iMum84Q2k-t-altETQ',
    appId: '1:1011770405028:web:fd747fa00e83b8cd207631',
    messagingSenderId: '1011770405028',
    projectId: 'chat-firebase-7a3e1',
    authDomain: 'chat-firebase-7a3e1.firebaseapp.com',
    storageBucket: 'chat-firebase-7a3e1.appspot.com',
    measurementId: 'G-VGQ93E29FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFJFFT0H3jvhSgAhayHRCq5s2MVPSfNj0',
    appId: '1:1011770405028:android:60281ff673c9dafd207631',
    messagingSenderId: '1011770405028',
    projectId: 'chat-firebase-7a3e1',
    storageBucket: 'chat-firebase-7a3e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0CQyKWaZsrW83j6LV3dFBMF0B_o6JvTA',
    appId: '1:1011770405028:ios:c8520684f54e30c3207631',
    messagingSenderId: '1011770405028',
    projectId: 'chat-firebase-7a3e1',
    storageBucket: 'chat-firebase-7a3e1.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0CQyKWaZsrW83j6LV3dFBMF0B_o6JvTA',
    appId: '1:1011770405028:ios:5561dc1ffca4e573207631',
    messagingSenderId: '1011770405028',
    projectId: 'chat-firebase-7a3e1',
    storageBucket: 'chat-firebase-7a3e1.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp.RunnerTests',
  );
}
